"use strict";
//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var tagService_ttypes = require('./tagService_types')
var entityService_ttypes = require('./entityService_types')


var ttypes = module.exports = {};
