"use strict";
//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var TagService_ttypes = require('./TagService_types')


var ttypes = require('./EntityService_types');
//HELPER FUNCTIONS AND STRUCTURES

var EntityService_createEntity_args = function(args) {
  this.entity = null;
  if (args) {
    if (args.entity !== undefined) {
      this.entity = args.entity;
    }
  }
};
EntityService_createEntity_args.prototype = {};
EntityService_createEntity_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.entity = new ttypes.Entity();
        this.entity.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EntityService_createEntity_args.prototype.write = function(output) {
  output.writeStructBegin('EntityService_createEntity_args');
  if (this.entity !== null && this.entity !== undefined) {
    output.writeFieldBegin('entity', Thrift.Type.STRUCT, 1);
    this.entity.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var EntityService_createEntity_result = function(args) {
  this.success = null;
  this.incorrectTag = null;
  if (args instanceof TagService_ttypes.IncorrectTag) {
    this.incorrectTag = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.incorrectTag !== undefined) {
      this.incorrectTag = args.incorrectTag;
    }
  }
};
EntityService_createEntity_result.prototype = {};
EntityService_createEntity_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.incorrectTag = new TagService_ttypes.IncorrectTag();
        this.incorrectTag.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EntityService_createEntity_result.prototype.write = function(output) {
  output.writeStructBegin('EntityService_createEntity_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  if (this.incorrectTag !== null && this.incorrectTag !== undefined) {
    output.writeFieldBegin('incorrectTag', Thrift.Type.STRUCT, 1);
    this.incorrectTag.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var EntityService_getEntity_args = function(args) {
  this.entityId = null;
  if (args) {
    if (args.entityId !== undefined) {
      this.entityId = args.entityId;
    }
  }
};
EntityService_getEntity_args.prototype = {};
EntityService_getEntity_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.entityId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EntityService_getEntity_args.prototype.write = function(output) {
  output.writeStructBegin('EntityService_getEntity_args');
  if (this.entityId !== null && this.entityId !== undefined) {
    output.writeFieldBegin('entityId', Thrift.Type.I32, 1);
    output.writeI32(this.entityId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var EntityService_getEntity_result = function(args) {
  this.success = null;
  this.incorrectEntity = null;
  if (args instanceof ttypes.IncorrectEntity) {
    this.incorrectEntity = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.incorrectEntity !== undefined) {
      this.incorrectEntity = args.incorrectEntity;
    }
  }
};
EntityService_getEntity_result.prototype = {};
EntityService_getEntity_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Entity();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.incorrectEntity = new ttypes.IncorrectEntity();
        this.incorrectEntity.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EntityService_getEntity_result.prototype.write = function(output) {
  output.writeStructBegin('EntityService_getEntity_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.incorrectEntity !== null && this.incorrectEntity !== undefined) {
    output.writeFieldBegin('incorrectEntity', Thrift.Type.STRUCT, 1);
    this.incorrectEntity.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var EntityServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
EntityServiceClient.prototype = {};
EntityServiceClient.prototype.seqid = function() { return this._seqid; }
EntityServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
EntityServiceClient.prototype.createEntity = function(entity, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_createEntity(entity);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_createEntity(entity);
  }
};

EntityServiceClient.prototype.send_createEntity = function(entity) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('createEntity', Thrift.MessageType.CALL, this.seqid());
  var args = new EntityService_createEntity_args();
  args.entity = entity;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

EntityServiceClient.prototype.recv_createEntity = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new EntityService_createEntity_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.incorrectTag) {
    return callback(result.incorrectTag);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('createEntity failed: unknown result');
};
EntityServiceClient.prototype.getEntity = function(entityId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getEntity(entityId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getEntity(entityId);
  }
};

EntityServiceClient.prototype.send_getEntity = function(entityId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getEntity', Thrift.MessageType.CALL, this.seqid());
  var args = new EntityService_getEntity_args();
  args.entityId = entityId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

EntityServiceClient.prototype.recv_getEntity = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new EntityService_getEntity_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.incorrectEntity) {
    return callback(result.incorrectEntity);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getEntity failed: unknown result');
};
var EntityServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
EntityServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

EntityServiceProcessor.prototype.process_createEntity = function(seqid, input, output) {
  var args = new EntityService_createEntity_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.createEntity.length === 1) {
    Q.fcall(this._handler.createEntity, args.entity)
      .then(function(result) {
        var result = new EntityService_createEntity_result({success: result});
        output.writeMessageBegin("createEntity", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new EntityService_createEntity_result(err);
        output.writeMessageBegin("createEntity", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.createEntity(args.entity,  function (err, result) {
      var result = new EntityService_createEntity_result((err != null ? err : {success: result}));
      output.writeMessageBegin("createEntity", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

EntityServiceProcessor.prototype.process_getEntity = function(seqid, input, output) {
  var args = new EntityService_getEntity_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getEntity.length === 1) {
    Q.fcall(this._handler.getEntity, args.entityId)
      .then(function(result) {
        var result = new EntityService_getEntity_result({success: result});
        output.writeMessageBegin("getEntity", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new EntityService_getEntity_result(err);
        output.writeMessageBegin("getEntity", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getEntity(args.entityId,  function (err, result) {
      var result = new EntityService_getEntity_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getEntity", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

