"use strict";
//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./tagService_types');
//HELPER FUNCTIONS AND STRUCTURES

var TagService_createTag_args = function(args) {
  this.tag = null;
  if (args) {
    if (args.tag !== undefined) {
      this.tag = args.tag;
    }
  }
};
TagService_createTag_args.prototype = {};
TagService_createTag_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.tag = new ttypes.Tag();
        this.tag.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TagService_createTag_args.prototype.write = function(output) {
  output.writeStructBegin('TagService_createTag_args');
  if (this.tag !== null && this.tag !== undefined) {
    output.writeFieldBegin('tag', Thrift.Type.STRUCT, 1);
    this.tag.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TagService_createTag_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
TagService_createTag_result.prototype = {};
TagService_createTag_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TagService_createTag_result.prototype.write = function(output) {
  output.writeStructBegin('TagService_createTag_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TagService_getTag_args = function(args) {
  this.tagId = null;
  if (args) {
    if (args.tagId !== undefined) {
      this.tagId = args.tagId;
    }
  }
};
TagService_getTag_args.prototype = {};
TagService_getTag_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.tagId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TagService_getTag_args.prototype.write = function(output) {
  output.writeStructBegin('TagService_getTag_args');
  if (this.tagId !== null && this.tagId !== undefined) {
    output.writeFieldBegin('tagId', Thrift.Type.I32, 1);
    output.writeI32(this.tagId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TagService_getTag_result = function(args) {
  this.success = null;
  this.incorrectTag = null;
  if (args instanceof ttypes.IncorrectTag) {
    this.incorrectTag = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.incorrectTag !== undefined) {
      this.incorrectTag = args.incorrectTag;
    }
  }
};
TagService_getTag_result.prototype = {};
TagService_getTag_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Tag();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.incorrectTag = new ttypes.IncorrectTag();
        this.incorrectTag.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TagService_getTag_result.prototype.write = function(output) {
  output.writeStructBegin('TagService_getTag_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.incorrectTag !== null && this.incorrectTag !== undefined) {
    output.writeFieldBegin('incorrectTag', Thrift.Type.STRUCT, 1);
    this.incorrectTag.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TagServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
TagServiceClient.prototype = {};
TagServiceClient.prototype.seqid = function() { return this._seqid; }
TagServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
TagServiceClient.prototype.createTag = function(tag, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_createTag(tag);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_createTag(tag);
  }
};

TagServiceClient.prototype.send_createTag = function(tag) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('createTag', Thrift.MessageType.CALL, this.seqid());
  var args = new TagService_createTag_args();
  args.tag = tag;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TagServiceClient.prototype.recv_createTag = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TagService_createTag_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('createTag failed: unknown result');
};
TagServiceClient.prototype.getTag = function(tagId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getTag(tagId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getTag(tagId);
  }
};

TagServiceClient.prototype.send_getTag = function(tagId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getTag', Thrift.MessageType.CALL, this.seqid());
  var args = new TagService_getTag_args();
  args.tagId = tagId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TagServiceClient.prototype.recv_getTag = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TagService_getTag_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.incorrectTag) {
    return callback(result.incorrectTag);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getTag failed: unknown result');
};
var TagServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
TagServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

TagServiceProcessor.prototype.process_createTag = function(seqid, input, output) {
  var args = new TagService_createTag_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.createTag.length === 1) {
    Q.fcall(this._handler.createTag, args.tag)
      .then(function(result) {
        var result = new TagService_createTag_result({success: result});
        output.writeMessageBegin("createTag", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new TagService_createTag_result(err);
        output.writeMessageBegin("createTag", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.createTag(args.tag,  function (err, result) {
      var result = new TagService_createTag_result((err != null ? err : {success: result}));
      output.writeMessageBegin("createTag", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

TagServiceProcessor.prototype.process_getTag = function(seqid, input, output) {
  var args = new TagService_getTag_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getTag.length === 1) {
    Q.fcall(this._handler.getTag, args.tagId)
      .then(function(result) {
        var result = new TagService_getTag_result({success: result});
        output.writeMessageBegin("getTag", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new TagService_getTag_result(err);
        output.writeMessageBegin("getTag", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getTag(args.tagId,  function (err, result) {
      var result = new TagService_getTag_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getTag", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

